# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 18:42
from __future__ import unicode_literals

import banuabla.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Profil Fotoğrafı')),
                ('fal_credit', models.IntegerField(default=0, verbose_name='Fal Baktırma Hakkı')),
                ('fal_point', models.IntegerField(default=0, verbose_name='Fal Puanı')),
                ('gender', models.CharField(blank=True, choices=[('K', 'Kadın'), ('E', 'Erkek')], default=None, max_length=1, null=True, verbose_name='Cinsiyeti')),
                ('birth', models.IntegerField(default=1900, verbose_name='Doğum Yılı')),
                ('login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Son Giriş IP')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Doğrulanmış')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Posta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('referanced_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Refansı')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', banuabla.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/', verbose_name='Fotoğraf')),
            ],
            options={
                'verbose_name_plural': 'Fotoğraflar',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Mesaj Zamanı')),
                ('content', models.TextField(max_length=1000, verbose_name='Mesaj İçeriği')),
            ],
            options={
                'verbose_name_plural': 'Sipariş Mesajları.',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Sipariş Zamanı')),
                ('fal_yorumu', models.FileField(null=True, upload_to='fal-yorumu', verbose_name='Fal Yorumu')),
                ('order_start', models.BooleanField(default=False, verbose_name='Sipariş Başladı')),
                ('order_status', models.BooleanField(default=False, verbose_name='Sipariş Tamamlandı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Siparişi Veren')),
            ],
            options={
                'verbose_name_plural': 'Siparişler',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banuabla.Order', verbose_name='Hangi Sipariş'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mesajın Sahibi'),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banuabla.Order', verbose_name='Sipariş'),
        ),
    ]
