# Generated by Django 2.1 on 2018-08-16 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0002_auto_20180816_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referanced_user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Refansı'),
        ),
    ]
