# Generated by Django 2.1 on 2018-10-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0003_auto_20180817_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='İsim')),
                ('comment', models.CharField(max_length=1024, verbose_name='Yorum')),
            ],
            options={
                'verbose_name_plural': 'Yorumlar',
            },
        ),
    ]
