# Generated by Django 2.1 on 2018-10-09 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgotcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
