# Generated by Django 2.1 on 2018-10-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0005_user_forgotcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_start',
        ),
    ]
