# Generated by Django 2.1 on 2018-10-16 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0006_remove_order_order_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Zamanı')),
                ('shopping_cart', models.IntegerField(choices=[(1, 'Tadımlık'), (3, 'Meraklı'), (5, 'Bağımlı')], verbose_name='Sepetteki Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satın Alan')),
            ],
            options={
                'verbose_name_plural': 'Satın Alma Sipariş',
            },
        ),
    ]
