# Generated by Django 2.1 on 2018-10-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0009_auto_20181017_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
