# Generated by Django 2.1 on 2018-10-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0010_buyorder_readonly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyorder',
            options={'verbose_name_plural': 'Kredi Siparişi'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Müşteri Yorumları'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Profil Fotoğraflı'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Fal Sipariş Mesajları'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Fal Siparişleri'},
        ),
    ]
