# Generated by Django 2.1 on 2018-10-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0011_auto_20181022_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Cinsiyetinizi Seçiniz'), ('K', 'Kadın'), ('E', 'Erkek')], default=None, max_length=1, null=True, verbose_name='Cinsiyeti'),
        ),
    ]
