# Generated by Django 2.1 on 2018-10-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0012_auto_20181025_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hakkında'),
        ),
    ]
