# Generated by Django 2.1.2 on 2018-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banuabla', '0013_user_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Fal Fotoğrafları'},
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hakkında'),
        ),
    ]
