# Generated by Django 2.1 on 2018-08-16 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('publish', models.BooleanField(default=False, verbose_name='Yayında')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('title_url', models.SlugField(max_length=255, verbose_name='Url')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('tags', models.CharField(max_length=500, verbose_name='Etiketler')),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name_plural': 'Yazılar',
            },
        ),
    ]
